import { StyleSheet } from 'react-native'

import { NAVBAR_HORIZONTAL_PADDING, NAVBAR_RADIUS, NAVBAR_VERTICAL_PADDING, SEARCH_BUTTON_HEIGHT } from '../constants/appConstants'

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#e2e8f0',
  },
  mapWrapper: {
    flex: 1,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  topPanel: {
    position: 'absolute',
    left: 12,
    right: 12,
    gap: 8,
    zIndex: 10,
    elevation: 10,
  },
  inputCard: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    shadowColor: '#0f172a',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  homeInputCard: {
    paddingVertical: 8,
    gap: 6,
  },
  input: {
    fontSize: 15,
    color: '#0f172a',
    paddingHorizontal: 6,
    paddingVertical: 8,
    paddingRight: 92,
  },
  homeInput: {
    flex: 1,
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '600',
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  homeSearchButton: {
    width: 42,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#020617',
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  clearButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchContainer: {
    zIndex: 100,
  },
  autocompleteDropdown: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 12,
    marginTop: 4,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    shadowColor: '#0f172a',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 6,
    maxHeight: 240,
    overflow: 'hidden',
  },
  autocompleteItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  autocompleteTextContainer: {
    flex: 1,
  },
  autocompleteMainText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0f172a',
  },
  autocompleteSecondaryText: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  selectedPlaceMarker: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  obstacleMarker: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.9)',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  obstacleMarkerBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  obstacleMarkerBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
  },
  obstacleInfoPanel: {
    position: 'absolute',
    left: 12,
    right: 12,
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#0f172a',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 8,
  },
  obstacleInfoLoading: {
    padding: 20,
    alignItems: 'center',
  },
  obstacleInfoTypeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    gap: 6,
    marginBottom: 10,
  },
  obstacleInfoTypeBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  obstacleInfoTypeBadgeCount: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 11,
    fontWeight: '500',
  },
  obstacleInfoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  obstacleInfoName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
    flex: 1,
    marginRight: 8,
  },
  obstacleInfoCloseButton: {
    padding: 4,
  },
  obstacleInfoDescription: {
    fontSize: 14,
    color: '#475569',
    lineHeight: 20,
    marginBottom: 12,
  },
  obstacleInfoImage: {
    width: '100%',
    height: 160,
    borderRadius: 12,
    marginBottom: 12,
    backgroundColor: '#e2e8f0',
  },
  obstacleInfoMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  obstacleInfoMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  obstacleInfoMetaText: {
    fontSize: 12,
    color: '#64748b',
  },
  placeInfoPanel: {
    position: 'absolute',
    left: 12,
    right: 12,
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#0f172a',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: -4 },
    elevation: 8,
  },
  placeInfoRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#f59e0b',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    gap: 4,
    marginBottom: 10,
  },
  placeInfoRatingBadgeText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  placeInfoRatingBadgeCount: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
  },
  placeInfoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  placeInfoName: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  placeInfoCloseButton: {
    padding: 4,
  },
  placeInfoAddress: {
    fontSize: 13,
    color: '#64748b',
    marginBottom: 10,
  },
  placeInfoOpenStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  placeInfoOpenDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  placeInfoOpenDotOpen: {
    backgroundColor: '#22c55e',
  },
  placeInfoOpenDotClosed: {
    backgroundColor: '#ef4444',
  },
  placeInfoOpenText: {
    fontSize: 13,
    fontWeight: '600',
  },
  placeInfoOpenTextOpen: {
    color: '#22c55e',
  },
  placeInfoOpenTextClosed: {
    color: '#ef4444',
  },
  placeInfoActions: {
    flexDirection: 'row',
    gap: 8,
  },
  placeInfoActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
  },
  placeInfoActionText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3b82f6',
  },
  inputDivider: {
    height: 1,
    backgroundColor: '#cbd5e1',
    marginRight: 84,
  },
  searchButton: {
    position: 'absolute',
    right: 10,
    minWidth: 68,
    height: SEARCH_BUTTON_HEIGHT,
    borderRadius: 17,
    backgroundColor: '#0f172a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    shadowColor: '#020617',
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  searchButtonCentered: {
    top: '50%',
    marginTop: -(SEARCH_BUTTON_HEIGHT / 2),
  },
  searchButtonText: {
    color: '#f8fafc',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '700',
    marginLeft: 4,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  mapTypeRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  mapTypeButton: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  mapTypeButtonActive: {
    backgroundColor: '#0f172a',
  },
  mapTypeButtonText: {
    fontWeight: '600',
    color: '#0f172a',
  },
  mapTypeButtonTextActive: {
    color: '#f8fafc',
  },
  focusButton: {
    position: 'absolute',
    right: 12,
    backgroundColor: '#0f172a',
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationError: {
    position: 'absolute',
    left: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    color: '#f8fafc',
    paddingHorizontal: 10,
    paddingVertical: NAVBAR_VERTICAL_PADDING,
    borderRadius: NAVBAR_RADIUS,
    fontSize: 12,
    overflow: 'hidden',
  },
  locationMarkerContainer: {
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  locationDotOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 2,
  },
  locationDotInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#4285F4',
  },
  headingConeWrapper: {
    position: 'absolute',
    width: 50,
    height: 50,
    alignItems: 'center',
    overflow: 'visible',
  },
  headingConeShape: {
    marginTop: 2,
    width: 0,
    height: 0,
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 10,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#4285F4',
  },
  bottomNav: {
    position: 'absolute',
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 20,
    gap: 8,
  },
  navGroup: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: NAVBAR_RADIUS,
    padding: 4,
    position: 'relative',
    overflow: 'hidden',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  navIndicator: {
    position: 'absolute',
    left: 4,
    top: 4,
    bottom: 4,
    backgroundColor: '#0f172a',
    borderRadius: 10,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    zIndex: 1,
  },
  navCameraButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 6,
    zIndex: 2,
  },
  navText: {
    color: '#475569',
    fontWeight: '600',
    fontSize: 12,
  },
  navTextActive: {
    color: '#f8fafc',
  },
  collapsiblePanel: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 0,
    zIndex: 15,
    elevation: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  panelHandleArea: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
    paddingBottom: 6,
    zIndex: 2,
  },
  panelHandle: {
    width: 46,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#cbd5e1',
  },
  navigationPanel: {
    backgroundColor: 'transparent',
    gap: 10,
    flex: 1,
  },
  navigationInputCard: {
    position: 'relative',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 10,
    gap: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  navigationHintCard: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationHintContent: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    maxWidth: 320,
  },
  navigationHintText: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
    lineHeight: 19,
    textAlign: 'center',
  },
  navigationHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navigationPanelTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  navigationDistancePill: {
    borderRadius: 999,
    backgroundColor: '#e2e8f0',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  navigationDistancePillText: {
    color: '#334155',
    fontSize: 11,
    fontWeight: '700',
  },
  navigationMetaRow: {
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  navigationMetaItem: {
    flex: 1,
  },
  navigationMetaLabel: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '600',
  },
  navigationMetaValue: {
    marginTop: 2,
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '800',
  },
  navigationMetaDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: '#e2e8f0',
    marginHorizontal: 8,
  },
  navigationRouteCard: {
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    gap: 6,
  },
  navigationRouteFrom: {
    fontSize: 13,
    color: '#0f172a',
    fontWeight: '700',
  },
  navigationRouteLine: {
    height: 1,
    backgroundColor: '#cbd5e1',
  },
  navigationRouteTo: {
    fontSize: 13,
    color: '#0f172a',
    fontWeight: '700',
  },
  navigationSteps: {
    gap: 7,
  },
  navigationStepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  navigationStepText: {
    flex: 1,
    fontSize: 12,
    color: '#334155',
    fontWeight: '600',
  },
  navigationStartButton: {
    marginTop: 2,
    borderRadius: 12,
    backgroundColor: '#0f172a',
    height: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  navigationStartButtonText: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
  },
  collapsibleContent: {
    flex: 1,
  },
  collapsibleContentInner: {
    padding: 12,
    flexGrow: 1,
  },
  panelTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 12,
  },
  transitUnavailableContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  transitUnavailableText: {
    fontSize: 14,
    color: '#334155',
    fontWeight: '700',
    textAlign: 'center',
  },
  profileContainer: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#e2e8f0',
  },
  profileScrollContent: {
    width: '100%',
    maxWidth: 440,
    paddingVertical: 24,
    paddingHorizontal: 16,
    gap: 14,
  },
  profileCard: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
  },
  profileText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#94a3b8',
    marginBottom: 8,
    textAlign: 'center',
  },
  profileValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 14,
    textAlign: 'center',
  },
  profileActions: {
    gap: 8,
  },
  changePasswordButton: {
    backgroundColor: '#0f172a',
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  changePasswordButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f8fafc',
    textAlign: 'center',
  },
  loginButton: {
    backgroundColor: '#0f172a',
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f8fafc',
    textAlign: 'center',
  },
  loggedInUsername: {
    fontSize: 16,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 24,
  },
  logoutButton: {
    backgroundColor: '#0f172a',
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f8fafc',
    textAlign: 'center',
  },
  badgesSection: {
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    alignItems: 'center'
  },
  badgesTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#94a3b8',
    marginBottom: 12,
  },
  badgesGrid: {
    flexDirection: 'column',
    gap: 12,
    width: '100%',
  },
  badgeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 14,
    gap: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  badgeIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  badgeContent: {
    flex: 1,
    gap: 4,
  },
  badgeName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  badgeDescription: {
    fontSize: 12,
    color: '#64748b',
    lineHeight: 16,
  },
  badgeImage: {
    width: 48,
    height: 48,
    resizeMode: 'contain',
  },
  badgeModalImage: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  modalContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 18,
    width: '100%',
    maxWidth: 360,
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    shadowColor: '#0f172a',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 6,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 4,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: '#0f172a',
  },
  modalButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  modalButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonCancel: {
    backgroundColor: '#e2e8f0',
  },
  modalButtonCancelText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
  },
  modalButtonSubmit: {
    backgroundColor: '#0f172a',
  },
  modalButtonSubmitText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f8fafc',
  },
  badgeModalContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 60,
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    shadowColor: '#0f172a',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 6,
  },
  badgeModalIcon: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  badgeModalIconText: {
    fontSize: 56,
  },
  badgeModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
  },
  badgeModalDescription: {
    fontSize: 13,
    color: '#475569',
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 18,
  },
  badgeModalCloseButton: {
    marginTop: 4,
    width: '100%',
    alignSelf: 'center',
  },
  languageSection: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
  },
  languageTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#94a3b8',
    marginBottom: 12,
    textAlign: 'center',
  },
  languageButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  languageButton: {
    flex: 1,
    backgroundColor: '#f8fafc',
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  languageButtonActive: {
    backgroundColor: '#0f172a',
    borderColor: '#0f172a',
  },
  languageButtonText: {
    fontWeight: '600',
    color: '#475569',
    fontSize: 14,
  },
  languageButtonTextActive: {
    color: '#f8fafc',
  },

  // Profile Panel Styles
  profilePanel: {
    gap: 12,
  },
  profileSectionCard: {
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  profileSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748b',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 14,
  },
  profileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarImage: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  profileInfo: {
    flex: 1,
  },
  profileUsername: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  profileEmail: {
    fontSize: 13,
    color: '#64748b',
    marginTop: 2,
  },
  profileLoginHint: {
    fontSize: 14,
    color: '#64748b',
  },
  profileButtonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  profileEditButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: '#e2e8f0',
  },
  profileEditButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
  },
  profileLogoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: '#fef2f2',
  },
  profileLogoutButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ef4444',
  },
  profileLoginButton: {
    backgroundColor: '#0f172a',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  profileLoginButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f8fafc',
  },
  googleLoginButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#ffffff',
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  googleIcon: {
    width: 18,
    height: 18,
  },
  googleLoginButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  settingLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#334155',
  },
  settingButtons: {
    flexDirection: 'row',
    gap: 6,
  },
  settingButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: '#e2e8f0',
  },
  settingButtonActive: {
    backgroundColor: '#0f172a',
  },
  settingButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
  },
  settingButtonTextActive: {
    color: '#f8fafc',
  },
  medalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  medalItem: {
    alignItems: 'center',
    width: 72,
  },
  medalIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  medalImage: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
  },
  medalName: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
    textAlign: 'center',
  },
  appInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  appInfoLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#334155',
  },
  appInfoValue: {
    fontSize: 14,
    color: '#64748b',
  },
  appInfoLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  appInfoLinkText: {
    fontSize: 14,
    color: '#3b82f6',
  },

  // Camera styles
  cameraContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  camera: {
    flex: 1,
  },
  cameraOverlay: {
    flex: 1,
    justifyContent: 'space-between',
    padding: 20,
  },
  cameraOverlayAbsolute: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    padding: 20,
  },
  cameraTopControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 40,
  },
  cameraControlButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraBottomControls: {
    alignItems: 'center',
    paddingBottom: 40,
  },
  cameraShutterButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: '#fff',
  },
  cameraShutterButtonInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#fff',
  },
  cameraPreview: {
    flex: 1,
  },
  cameraPreviewActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    padding: 24,
    paddingBottom: 48,
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  cameraActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
  },
  cameraActionButtonPrimary: {
    backgroundColor: '#0f172a',
  },
  cameraActionButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },
  cameraActionButtonTextPrimary: {
    color: '#f8fafc',
  },
  cameraPermissionContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    gap: 16,
  },
  cameraPermissionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#f8fafc',
    textAlign: 'center',
  },
  cameraPermissionText: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
  },
  cameraPermissionButton: {
    marginTop: 8,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
  },
  cameraPermissionButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0f172a',
  },

  // Report Form styles
  reportFormContainer: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  reportFormContent: {
    padding: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  reportPhotoPreview: {
    position: 'relative',
    width: 120,
    height: 120,
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 24,
    alignSelf: 'center',
  },
  reportPhotoImage: {
    width: '100%',
    height: '100%',
  },
  reportPhotoRetake: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportInputGroup: {
    marginBottom: 20,
  },
  reportInputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
    marginBottom: 8,
  },
  reportInput: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#0f172a',
  },
  reportInputMultiline: {
    minHeight: 100,
    paddingTop: 12,
  },
  reportTypeButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  reportTypeButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
  },
  reportTypeButtonActive: {
    backgroundColor: '#0f172a',
    borderColor: '#0f172a',
  },
  reportTypeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
  },
  reportTypeButtonTextActive: {
    color: '#f8fafc',
  },
  reportLocationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
    marginBottom: 24,
  },
  reportLocationText: {
    fontSize: 13,
    color: '#64748b',
  },
  reportActions: {
    flexDirection: 'row',
    gap: 12,
  },
  reportCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportCancelButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#475569',
  },
  reportSubmitButton: {
    flex: 2,
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportSubmitButtonDisabled: {
    opacity: 0.6,
  },
  reportSubmitButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#f8fafc',
  },
})

