import { StyleSheet } from 'react-native'

import { NAVBAR_HORIZONTAL_PADDING, NAVBAR_RADIUS, NAVBAR_VERTICAL_PADDING, SEARCH_BUTTON_HEIGHT } from '../constants/appConstants'

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#e2e8f0',
  },
  mapWrapper: {
    flex: 1,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  topPanel: {
    position: 'absolute',
    left: 12,
    right: 12,
    gap: 8,
    zIndex: 10,
    elevation: 10,
  },
  inputCard: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 14,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    shadowColor: '#0f172a',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  homeInputCard: {
    paddingVertical: 8,
    gap: 6,
  },
  input: {
    fontSize: 15,
    color: '#0f172a',
    paddingHorizontal: 6,
    paddingVertical: 8,
    paddingRight: 92,
  },
  homeInput: {
    flex: 1,
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '600',
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  homeSearchButton: {
    width: 42,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#020617',
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  inputDivider: {
    height: 1,
    backgroundColor: '#cbd5e1',
    marginRight: 84,
  },
  searchButton: {
    position: 'absolute',
    right: 10,
    minWidth: 68,
    height: SEARCH_BUTTON_HEIGHT,
    borderRadius: 17,
    backgroundColor: '#0f172a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    shadowColor: '#020617',
    shadowOpacity: 0.24,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  searchButtonCentered: {
    top: '50%',
    marginTop: -(SEARCH_BUTTON_HEIGHT / 2),
  },
  searchButtonText: {
    color: '#f8fafc',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '700',
    marginLeft: 4,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  mapTypeRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  mapTypeButton: {
    backgroundColor: 'rgba(255,255,255,0.92)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  mapTypeButtonActive: {
    backgroundColor: '#0f172a',
  },
  mapTypeButtonText: {
    fontWeight: '600',
    color: '#0f172a',
  },
  mapTypeButtonTextActive: {
    color: '#f8fafc',
  },
  focusButton: {
    position: 'absolute',
    right: 12,
    backgroundColor: '#0f172a',
    width: 44,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationError: {
    position: 'absolute',
    left: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    color: '#f8fafc',
    paddingHorizontal: 10,
    paddingVertical: NAVBAR_VERTICAL_PADDING,
    borderRadius: NAVBAR_RADIUS,
    fontSize: 12,
    overflow: 'hidden',
  },
  locationDotOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(59, 130, 246, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.7)',
  },
  locationDotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2563eb',
  },
  bottomNav: {
    position: 'absolute',
    left: 12,
    right: 12,
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: NAVBAR_RADIUS,
    paddingVertical: NAVBAR_VERTICAL_PADDING,
    paddingHorizontal: NAVBAR_HORIZONTAL_PADDING,
    zIndex: 20,
    elevation: 20,
    overflow: 'hidden',
  },
  navIndicator: {
    position: 'absolute',
    left: NAVBAR_HORIZONTAL_PADDING,
    top: NAVBAR_VERTICAL_PADDING,
    bottom: NAVBAR_VERTICAL_PADDING,
    backgroundColor: '#0f172a',
    borderRadius: 10,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 10,
    zIndex: 1,
  },
  navText: {
    color: '#475569',
    fontWeight: '600',
    fontSize: 12,
  },
  navTextActive: {
    color: '#f8fafc',
  },
  collapsiblePanel: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 0,
    zIndex: 15,
    elevation: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  panelHandleArea: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
    paddingBottom: 6,
    zIndex: 2,
  },
  panelHandle: {
    width: 46,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#cbd5e1',
  },
  navigationPanel: {
    backgroundColor: 'transparent',
    gap: 10,
    flex: 1,
  },
  navigationInputCard: {
    position: 'relative',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 10,
    gap: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  navigationHintCard: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationHintContent: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    maxWidth: 320,
  },
  navigationHintText: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
    lineHeight: 19,
    textAlign: 'center',
  },
  navigationHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navigationPanelTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  navigationDistancePill: {
    borderRadius: 999,
    backgroundColor: '#e2e8f0',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  navigationDistancePillText: {
    color: '#334155',
    fontSize: 11,
    fontWeight: '700',
  },
  navigationMetaRow: {
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  navigationMetaItem: {
    flex: 1,
  },
  navigationMetaLabel: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '600',
  },
  navigationMetaValue: {
    marginTop: 2,
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '800',
  },
  navigationMetaDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: '#e2e8f0',
    marginHorizontal: 8,
  },
  navigationRouteCard: {
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    gap: 6,
  },
  navigationRouteFrom: {
    fontSize: 13,
    color: '#0f172a',
    fontWeight: '700',
  },
  navigationRouteLine: {
    height: 1,
    backgroundColor: '#cbd5e1',
  },
  navigationRouteTo: {
    fontSize: 13,
    color: '#0f172a',
    fontWeight: '700',
  },
  navigationSteps: {
    gap: 7,
  },
  navigationStepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  navigationStepText: {
    flex: 1,
    fontSize: 12,
    color: '#334155',
    fontWeight: '600',
  },
  navigationStartButton: {
    marginTop: 2,
    borderRadius: 12,
    backgroundColor: '#0f172a',
    height: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  navigationStartButtonText: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
  },
  collapsibleContent: {
    padding: 12,
    flex: 1,
  },
  transitButtonRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    gap: 8,
    marginTop: 0,
  },
  collapsibleTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 6,
  },
  collapsibleText: {
    fontSize: 13,
    color: '#475569',
  },
  transitCardsContainer: {
    marginTop: 16,
    gap: 12,
  },
  transitCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.05)',
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#2563eb',
  },
  transitCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  routeName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  arrivalTime: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2563eb',
  },
  transitCardBody: {
    gap: 6,
  },
  transitInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  transitLabel: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '600',
  },
  transitValue: {
    fontSize: 12,
    color: '#0f172a',
    fontWeight: '600',
  },
  profileContainer: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#e2e8f0',
  },
  profileScrollContent: {
    width: '100%',
    maxWidth: 440,
    paddingVertical: 24,
    paddingHorizontal: 16,
    gap: 14,
  },
  profileCard: {
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
  },
  profileText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#94a3b8',
    marginBottom: 8,
    textAlign: 'center',
  },
  profileValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 14,
    textAlign: 'center',
  },
  profileActions: {
    gap: 8,
  },
  changePasswordButton: {
    backgroundColor: '#0f172a',
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  changePasswordButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f8fafc',
    textAlign: 'center',
  },
  loginButton: {
    backgroundColor: '#0f172a',
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f8fafc',
    textAlign: 'center',
  },
  loggedInUsername: {
    fontSize: 16,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 24,
  },
  logoutButton: {
    backgroundColor: '#0f172a',
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoutButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f8fafc',
    textAlign: 'center',
  },
  badgesSection: {
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    alignItems: 'center'
  },
  badgesTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#94a3b8',
    marginBottom: 12,
  },
  badgesGrid: {
    flexDirection: 'column',
    gap: 12,
    width: '100%',
  },
  badgeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 14,
    gap: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  badgeIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  badgeContent: {
    flex: 1,
    gap: 4,
  },
  badgeName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  badgeDescription: {
    fontSize: 12,
    color: '#64748b',
    lineHeight: 16,
  },
  badgeImage: {
    width: 48,
    height: 48,
    resizeMode: 'contain',
  },
  badgeModalImage: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  modalContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 18,
    width: '100%',
    maxWidth: 360,
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    shadowColor: '#0f172a',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 6,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 4,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: '#0f172a',
  },
  modalButtonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  modalButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonCancel: {
    backgroundColor: '#e2e8f0',
  },
  modalButtonCancelText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
  },
  modalButtonSubmit: {
    backgroundColor: '#0f172a',
  },
  modalButtonSubmitText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#f8fafc',
  },
  badgeModalContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 60,
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    shadowColor: '#0f172a',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 6,
  },
  badgeModalIcon: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  badgeModalIconText: {
    fontSize: 56,
  },
  badgeModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
  },
  badgeModalDescription: {
    fontSize: 13,
    color: '#475569',
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 18,
  },
  badgeModalCloseButton: {
    marginTop: 4,
    width: '100%',
    alignSelf: 'center',
  },
})

